#include <stdio.h>

#define NOT(x) (!(x))
#define OR(x, y) ((x) || (y))
#define AND(x, y) ((x) && (y))
#define OUTPUT(x) (x)

#define FIRST(A, ...) A
#define REST(A, ...) __VA_ARGS__

#define NTH_1(...) FIRST(__VA_ARGS__)

#define NTH_2(...) NTH_1(REST(__VA_ARGS__))


#define __OR_3__OR_2(__OR_3__INPUT_1, __OR_3__INPUT_2, __OR_3__INPUT_3) OR(NTH_1(__OR_3__INPUT_1), NTH_1(__OR_3__INPUT_2))
#define __OR_3__OR_1(__OR_3__INPUT_1, __OR_3__INPUT_2, __OR_3__INPUT_3) OR(NTH_1(__OR_3__OR_2(__OR_3__INPUT_1, __OR_3__INPUT_2, __OR_3__INPUT_3)), NTH_1(__OR_3__INPUT_3))
#define __OR_3__OUTPUT_1(__OR_3__INPUT_1, __OR_3__INPUT_2, __OR_3__INPUT_3) OUTPUT(NTH_1(__OR_3__OR_1(__OR_3__INPUT_1, __OR_3__INPUT_2, __OR_3__INPUT_3)))
#define OR_3(__OR_3__INPUT_1, __OR_3__INPUT_2, __OR_3__INPUT_3) __OR_3__OUTPUT_1(__OR_3__INPUT_1, __OR_3__INPUT_2, __OR_3__INPUT_3)

#define __AND_3__AND_1(__AND_3__INPUT_1, __AND_3__INPUT_2, __AND_3__INPUT_3) AND(NTH_1(__AND_3__INPUT_1), NTH_1(__AND_3__INPUT_2))
#define __AND_3__AND_2(__AND_3__INPUT_1, __AND_3__INPUT_2, __AND_3__INPUT_3) AND(NTH_1(__AND_3__AND_1(__AND_3__INPUT_1, __AND_3__INPUT_2, __AND_3__INPUT_3)), NTH_1(__AND_3__INPUT_3))
#define __AND_3__OUTPUT_1(__AND_3__INPUT_1, __AND_3__INPUT_2, __AND_3__INPUT_3) OUTPUT(NTH_1(__AND_3__AND_2(__AND_3__INPUT_1, __AND_3__INPUT_2, __AND_3__INPUT_3)))
#define AND_3(__AND_3__INPUT_1, __AND_3__INPUT_2, __AND_3__INPUT_3) __AND_3__OUTPUT_1(__AND_3__INPUT_1, __AND_3__INPUT_2, __AND_3__INPUT_3)

#define __MAIN__AND_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) AND(NTH_1(__MAIN__INPUT_1), NTH_1(__MAIN__INPUT_2))
#define __MAIN__AND_2(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) AND(NTH_1(__MAIN__INPUT_1), NTH_1(__MAIN__INPUT_3))
#define __MAIN__OR_3_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) OR_3(NTH_1(__MAIN__INPUT_1), NTH_1(__MAIN__INPUT_2), NTH_1(__MAIN__INPUT_3))
#define __MAIN__AND_3(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) AND(NTH_1(__MAIN__INPUT_2), NTH_1(__MAIN__INPUT_3))
#define __MAIN__AND_3_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) AND_3(NTH_1(__MAIN__INPUT_1), NTH_1(__MAIN__INPUT_2), NTH_1(__MAIN__INPUT_3))
#define __MAIN__OR_3_2(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) OR_3(NTH_1(__MAIN__AND_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)), NTH_1(__MAIN__AND_2(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)), NTH_1(__MAIN__AND_3(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)))
#define __MAIN__OUTPUT_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) OUTPUT(NTH_1(__MAIN__OR_3_2(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)))
#define __MAIN__AND_4(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) AND(NTH_1(__MAIN__OR_3_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)), NTH_1(__MAIN__NOT_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)))
#define __MAIN__NOT_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) NOT(NTH_1(__MAIN__OR_3_2(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)))
#define __MAIN__OR_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) OR(NTH_1(__MAIN__AND_3_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)), NTH_1(__MAIN__AND_4(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)))
#define __MAIN__OUTPUT_2(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) OUTPUT(NTH_1(__MAIN__OR_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)))
#define MAIN(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3) __MAIN__OUTPUT_1(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3), __MAIN__OUTPUT_2(__MAIN__INPUT_1, __MAIN__INPUT_2, __MAIN__INPUT_3)



int main(void) {
}